export const bodyPartsData = [
  {
    bodyPartName: "head",
    bodyPartProportion: 4.5,
    id: 0,
    frontSide: true,
    backSide: true,
    isFrontChecked: false,
    isBackChecked: false,
  },
  {
    bodyPartName: "corpus",
    bodyPartProportion: 18,
    id: 1,
    frontSide: true,
    backSide: true,
    isFrontChecked: false,
    isBackChecked: false,
  },
  {
    bodyPartName: "left-arm",
    bodyPartProportion: 4.5,
    id: 2,
    frontSide: true,
    backSide: true,
    isFrontChecked: false,
    isBackChecked: false,
  },
  {
    bodyPartName: "right-arm",
    bodyPartProportion: 4.5,
    id: 3,
    frontSide: true,
    backSide: true,
    isFrontChecked: false,
    isBackChecked: false,
  },
  {
    bodyPartName: "crotch",
    bodyPartProportion: 1,
    id: 4,
    frontSide: true,
    backSide: false,
    isFrontChecked: false,
    isBackChecked: false,
  },
  {
    bodyPartName: "left-leg",
    bodyPartProportion: 9,
    id: 5,
    frontSide: true,
    backSide: true,
    isFrontChecked: false,
    isBackChecked: false,
  },
  {
    bodyPartName: "right-leg",
    bodyPartProportion: 9,
    id: 6,
    frontSide: true,
    backSide: true,
    isFrontChecked: false,
    isBackChecked: false,
  },
];

export const symptoms = [
  {
    name: "erythema",
    polishLabel: "Rumień",
  },
  { name: "edema", polishLabel: "Obrzęk" },
  { name: "oozing-crusting", polishLabel: "Wysięki i strupki" },
  { name: "lichenification", polishLabel: "Zgrubienie skóry" },
  {
    name: "scratch-marks",
    polishLabel: "Przeczosy (uszkodzenia od drapania)",
  },
  {
    name: "dryness",
    polishLabel: "Suchość (na obszarach niezajętych zmianami zapalnymi",
  },
];
